version = 1

test_patterns = ["**/*.test.ts"]

exclude_patterns = [
  "/dist/**.*",
  "**/*-old.*"
]

[[analyzers]]
name = "javascript"
enabled = true

[[transformers]]
name = "prettier"
enabled = false

[[transformers]]
name = "standardjs"
enabled = false